### PR TITLE
Read manifest of JAR file instead of first manifest on classpath

### PR DESCRIPTION
**Pull request by marcphilipp**
Fix for problem in junit-team/junit5#640.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sormuras** [comment]
The outer `try { ... }` is not necessary. Could be cleaned up to:
```
		CodeSource codeSource = type.getProtectionDomain().getCodeSource();
		URL jarUrl = codeSource.getLocation();
		try (JarFile jarFile = new JarFile(new File(jarUrl.toURI()))) {
			Manifest manifest = jarFile.getManifest();
			Attributes mainAttributes = manifest.getMainAttributes();
			return Optional.ofNullable(mainAttributes.getValue(name));
		}
		catch (Exception e) {
			return Optional.empty();
		}

```

**Comment by marcphilipp** [comment]
I left it in because `getProtectionDomain()` might throw a `SecurityException`.

**Comment by sormuras** [comment]
I see.

**Comment by sormuras** [comment]
Writing `		catch (SecurityException | URISyntaxException | IOException e) {
			return Optional.empty();
		}` is an overkill, right?

**Comment by marcphilipp** [comment]
I just thought we might even need to handle `SecurityException` in `TestEngine#getVersion` because if we don't then we'll accidentally always use the implementation version of junit-platform-console. It's more of an edge case... what do you think?

**Comment by marcphilipp** [comment]
I decided to merge junit-team/junit5#640. We always improve that code in a separate PR. 😉

**Comment by sormuras** [comment]
Totally fine with me.

**Pull request merged**
